# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GameDevUtils.com
email: hello@gamedevutils.com
tagline: More tools. More platforms.

# author: Contact Us
#description: >- # this means to ignore newlines until "baseurl:"
#  I created GameDevUtils.com for my game programming students
#  to have access to high-quality, free tools. The goals of the
#  project are to create tools that rival the
#  for-pay apps in functionality and design, to provide access to
#  the source code for those tools, and to get my students excited about
#  game programming by making many of the more tedious production tasks easier.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username:  groundh0g
twitter_username:   groundh0g
youtube_username:   groundh0g
github_username:    groundh0g
linkedin_username:  groundh0g
pinterest_username: groundh0g
instagram_username: groundh0g72
twitch_username:    groundh0gXNA
rss: RSS

author:
  name: Administrator
  twitter: gamedevutils

# Build settings
markdown: kramdown
show_excerpts: true
#theme: minima


# custom feed logic for localization
feedify:
  generator:
    home: GameDevUtils.com
    name: GameDevUtils.com L10N Feedify
    uri: http://GameDevUtils.com/
    version: 0.1.0

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

google_analytics: UA-3294285-9

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
